[profile.default]
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 200

src = "src"
out = "out"
libs = ["lib", "dependencies"]

remappings = ["@battlechips/=src", "@lib/=lib", "@test/=test"]

fuzz_runs = 1000

[profile.ci]
verbosity = 4

gas_reports = ["pvp"]

[dependencies]
forge-std = "1.9.3"
"@openzeppelin-contracts" = "5.1.0"
solady = "0.0.267"


[soldeer]
remappings_generate = true
remappings_regenerate = true
remappings_version = false

# Config
[rpc_endpoints]
sei = "${SEI_RPC_URL}"

[etherscan]
1329 = { key = "${SEI_TRACE_API_KEY}", url = "https://seitrace.com/atlantic-2/api" }
